[package]
name = "majdataplay-multiuser"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
eframe = "0.30.0"
egui = "0.30.0"
egui-modal = "0.6.0"
egui-notify = "0.18.0"
subprocess = "0.2.9"
thiserror = "2.0.12"
